const KYC_STATUSES = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  VERIFIED: 'VERIFIED',
  FAILED: 'FAILED',
  RESUBMISSION_REQUIRED: 'RESUBMISSION_REQUIRED',
};

const VERIFICATION_TX_STATUSES = {
  NONE: 'NONE',
  PENDING: 'PENDING',
  SUBMITTED: 'SUBMITTED',
  CONFIRMED: 'CONFIRMED',
  FAILED: 'FAILED',
};

const KYC_ACTIONS = {
  SUBMITTED: 'APPLICATION_SUBMITTED',
  UPDATED: 'APPLICATION_UPDATED',
  REVIEW_OPENED: 'REVIEW_OPENED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  APPROVED: 'APPLICATION_APPROVED',
  REJECTED: 'APPLICATION_REJECTED',
  RESUBMISSION_REQUESTED: 'RESUBMISSION_REQUESTED',
  REVIEW_STARTED: 'REVIEW_STARTED',
  VERIFY_ONCHAIN_REQUESTED: 'VERIFY_ONCHAIN_REQUESTED',
  VERIFY_ONCHAIN_SUCCEEDED: 'VERIFY_ONCHAIN_SUCCEEDED',
  VERIFY_ONCHAIN_FAILED: 'VERIFY_ONCHAIN_FAILED',
};

module.exports = {
  KYC_STATUSES,
  VERIFICATION_TX_STATUSES,
  KYC_ACTIONS,
};
